id: P6F8985C9
initial_creation_type: input
source_metadata:
  title: Tertön Sogyal Series
  language: es
  description: 'Texts by and about the famous treasure-revealer and teacher of the
    Thirteenth Dalai Lama, Tertön Sogyal Lerab Lingpa (gter ston bsod rgyal las rab
    gling pa, 1856-1926):'
  volume:
    dfe52b1c78ef4b889c85ccb017ad29b5:
      title: Advice from the Lips of Tertön Sogyal
      parent: Advice
    32440ad60a674082b2b2330e73eb0302:
      title: From the Oral Tradition of the Lama of Nyarong
      parent: Advice
    fc255a434057441b8fc9bad7d33618f9:
      title: Prayer for the Flourishing of the Teachings
      parent: Aspiration Prayers
    234e18096b1e42be9fe5dfb0626ab0cd:
      title: Brief Prayer for Pacifying the Turmoil of the Mamos
      parent: Dharma Protectors
    304169d2b12748c7a07d6fff5b774e5a:
      title: Serkyem (Golden Libation) Offering to the Guardians of the Tradition
      parent: Dharma Protectors
    7e330482358f4bb584573f18a5373fb4:
      title: Brief Explanation of Clarification and Transcendental Resolution from
        the Oral Tradition of Nyala Sogyal
      parent: Dzogchen
    12ff367203f84912b53f6c2f72b46bb0:
      title: Guru Yoga
      parent: Guru Yoga
    df82ff49bc4e4741b7fede6dd3e76fa7:
      title: The Guru Yoga of the Profound Path
      parent: Guru Yoga
    43a5b6d23d504f47ab7e36f91eecbb57:
      title: A Vajrakīla Lineage Prayer
      parent: Lineage Prayers
    5b26a35b84db43abbe8567d24b78edf3:
      title: 'The Sweet Song of Māra''s Defeat: A Prayer for the Long Life of the
        Great Tertön and Vidyādhara Lerab Lingpa'
      parent: Long Life Prayers
    4b9052e7a7de48f4938bedbda129e7be:
      title: The Seeds of Faith, A Prayer to the Vidyādhara and Great Tertön Lerab
        Lingpa
      parent: Prayers
    93a527a0020d43999ae745c9d7d9ffe0:
      title: Sādhana of Mañjughoṣa
      parent: Sādhanas
    efeae9f838cf48f69bdef299dd507e08:
      title: The Method to Pacify All Epidemics, Illnesses and Pandemics from the
        Sixty Solitary Forms of Yamāntaka
      parent: Sādhanas
    5ef42b9eacd742aab4dbae34d8ed0c5c:
      title: 'The Swift Path to Great Bliss: A Sādhana of Amitābha, Buddha of Limitless
        Light'
      parent: Sādhanas
    47e7087453814db5aa4e836251bd6305:
      title: A Lamenting Plea for Compassion
      parent: Songs
    54a8890cdb4d4e9da3256e1034037f07:
      title: A Synopsis of the Vajra-Guru Mantra
      parent: Vajra Guru Mantra
    870dda53f33f47d2bb19204209f7fcf5:
      title: 'Inventory: The Perfectly Clear Mirror from the Razor of the Innermost
        Essence'
      parent: Vajrakīla
    54b36b703a744323beb409082362d9e5:
      title: 'The Falling Rain of Blessings: A Prayer of Inspiration'
      parent: Vajrakīla
    3b75a117686f4aa7bfa815c74c271bdd:
      title: The Summoning of Blessings which Brings them Swift and Fast
      parent: Vajrakīla
    18ee3c06a738417286078e3b1816dcec:
      title: The Ultimate, Natural Dispeller of Obstacles
      parent: Vajrakīla
    eec572c280fe43f59988ee5255d32fff:
      title: The Wisdom Mind Practice of One Kīla
      parent: Vajrakīla
    f8d5d097eb2f4b4cb6d477826946f96a:
      title: The Twenty-Eight Commitments
      parent: Tantra
created_at: '2022-03-01T01:44:22.624794'
last_modified_at: '2022-03-01T01:44:22.624797'
